### ISSUE TITLE
Not possible to print text in circuitpython to Feather M0 express with SSD1306 oled shield

### ISSUE THREAD

**Issue by smart-t** [adafruit/Adafruit_CircuitPython_SSD1306#2]
```Adafruit CircuitPython 0.9.4 on 2017-04-10; Adafruit Feather M0 Express with samd21g18
>>> import adafruit_ssd1306 as ssd1306
>>> from board import *
>>> import busio
>>> i2c = busio.I2C(SCL, SDA)
>>> oled = ssd1306.SSD1306_I2C(128, 32, i2c)
>>> oled.fill(0)
>>> oled.show()
>>> oled.text('Hello', 0, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ssd1306/ssd1306.py", line 102, in text
TypeError: function takes 1 positional arguments but 5 were given
>>> ```

It looks like the framebuf.mpy is not fully implemented.

**Comment by tannewt** [comment]
I'm going to move this to the framebuf repo. https://github.com/adafruit/micropython-adafruit-framebuf/issues/2
