### ISSUE TITLE
Could not find font file font5x8.bin/invalid font file

### ISSUE THREAD

**Issue by kittenarmy** [adafruit/Adafruit_CircuitPython_SSD1306#87]
I'm trying to use this with Blinka on Raspberry Pi 3B with Bookworm, following [these](https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/running-circuitpython-code-without-circuitpython) [guides](https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi#setup-virtual-environment-3157129).

I get this error when I run a test script: 

```Could not find font file font5x8.bin
Traceback (most recent call last):
  File "/home/pi/oled-test.py", line 28, in <module>
    display.text("Hello", 0, 0, 1)
  File "/home/pi/env/lib/python3.11/site-packages/adafruit_framebuf.py", line 507, in text
    self._font = BitmapFont(font_name)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/env/lib/python3.11/site-packages/adafruit_framebuf.py", line 580, in __init__
    self._font = open(  # pylint: disable=consider-using-with
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'font5x8.bin'
```

I saw this issue https://github.com/adafruit/Adafruit_CircuitPython_framebuf/issues/38 so downloaded with `wget https://github.com/adafruit/Adafruit_CircuitPython_framebuf/tree/main/examples/font5x8.bin` and get this error:

```
Traceback (most recent call last):
  File "/home/pi/oled-test.py", line 28, in <module>
    display.text("Hello", 0, 0, 1)
  File "/home/pi/env/lib/python3.11/site-packages/adafruit_framebuf.py", line 507, in text
    self._font = BitmapFont(font_name)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/env/lib/python3.11/site-packages/adafruit_framebuf.py", line 586, in __init__
    raise RuntimeError("Invalid font file: " + font_name)
RuntimeError: Invalid font file: font5x8.bin
```

My code:

```
# Import all board pins.
from board import SCL, SDA
import busio

# Import the SSD1306 module.
import adafruit_ssd1306

# Create the I2C interface.
i2c = busio.I2C(SCL, SDA)

# Create the SSD1306 OLED class.
# The first two parameters are the pixel width and pixel height.  Change these
# to the right size for your display!
display = adafruit_ssd1306.SSD1306_I2C(128, 32, i2c)
# Alternatively you can change the I2C address of the device with an addr param>
#display = adafruit_ssd1306.SSD1306_I2C(128, 32, i2c, addr=0x31)
# Clear the display.  Always call show after changing pixels to make the display
# update visible!
display.fill(0)
display.show()

# x y color
display.text("Hello", 0, 0, 1)
display.text("World", 0, 10, 1)
display.show()
```

**Comment by kittenarmy** [comment]
Fixed it by downloading this way: 
```
(env) pi@raspberrypi:~ $ rm font5x8.bin
(env) pi@raspberrypi:~ $ sudo wget -O font5x8.bin https://github.com/adafruit/Adafruit_CircuitPython_framebuf/blob/main/examples/font5x8.bin?raw=true
```
